### ISSUE TITLE
WARNING:absl:not exist in w2v model: 万能

### ISSUE THREAD

**Issue by dragononly** [chatopera/Synonyms#103]
一堆这样的新词警告怎么处理？

**Comment by jishengwei** [comment]
sysnonyms.py文件中注释掉“logging.warning("not exist in w2v model: %s" % y_)”

**Comment by Samurais** [comment]
![image](https://user-images.githubusercontent.com/3538629/94803829-7d236880-041c-11eb-963c-3bbfb3412def.png)

使用最新版本，可以获得词向量了。
但是，近义词效果不佳。

**Comment by Samurais** [comment]
不建议去掉注释，可以提交到 Github 里，下次优化。
