### ISSUE TITLE
absl:not exist in w2v model

### ISSUE THREAD

**Issue by isblwang** [chatopera/Synonyms#104]
# description
    sen1 = "发动机异响"
    sen2 = "引擎啸叫"

    print(synonyms.v('响声'))
    r = synonyms.compare(sen1, sen2, seg=True)
    print(r)

## current
WARNING:absl:not exist in w2v model: 啸叫
## expected
相似度为0.9XXX
# solution

# environment

* version:
The commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
使用最新版本，已经解决。

![image](https://user-images.githubusercontent.com/3538629/94803765-63822100-041c-11eb-8dab-746f7c813b4b.png)

**Comment by isblwang** [comment]
谢谢！
