### ISSUE TITLE
WARNING:absl:not exist in w2v model: 全脂奶粉

### ISSUE THREAD

**Issue by cancerwower** [chatopera/Synonyms#106]
# description
lack of these words???
## current
WARNING:absl:not exist in w2v model: 全脂奶粉
WARNING:absl:not exist in w2v model: 原装
WARNING:absl:not exist in w2v model: 脱脂奶粉
WARNING:absl:not exist in w2v model: 原装
WARNING:absl:not exist in w2v model: 全脂奶粉
WARNING:absl:not exist in w2v model: 原装
WARNING:absl:not exist in w2v model: 包邮
WARNING:absl:not exist in w2v model: 原装
WARNING:absl:not exist in w2v model: mymy
WARNING:absl:not exist in w2v model: 全脂
WARNING:absl:not exist in w2v model: 全脂奶粉
WARNING:absl:not exist in w2v model: 原装
WARNING:absl:not exist in w2v model: 原装
WARNING:absl:not exist in w2v model: 全脂奶粉
WARNING:absl:not exist in w2v model: 营养早餐
WARNING:absl:not exist in w2v model: 全脂奶粉
WARNING:absl:not exist in w2v model: 原装
WARNING:absl:not exist in w2v model: 全脂奶粉
WARNING:absl:not exist in w2v model: 醇香
WARNING:absl:not exist in w2v model: 全脂奶粉
WARNING:absl:not exist in w2v model: 原装
WARNING:absl:not exist in w2v model: 包邮
WARNING:absl:not exist in w2v model: 脱脂奶粉
WARNING:absl:not exist in w2v model: 全脂奶粉
WARNING:absl:not exist in w2v model: 原装
WARNING:absl:not exist in w2v model: 原装
WARNING:absl:not exist in w2v model: 全脂
WARNING:absl:not exist in w2v model: 速溶
WARNING:absl:not exist in w2v model: 59
WARNING:absl:not exist in w2v model: 包邮
WARNING:absl:not exist in w2v model: 全脂奶粉
WARNING:absl:not exist in w2v model: 原装
WARNING:absl:not exist in w2v model: 一袋
WARNING:absl:not exist in w2v model: 包邮
WARNING:absl:not exist in w2v model: 全脂奶粉

## expected

# solution

# environment
centos7 
* version:3.10.2
The commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
使用最新版本，更大词汇表。

![image](https://user-images.githubusercontent.com/3538629/94803524-025a4d80-041c-11eb-8f2f-e22b97d3214c.png)

目前看效果还是有限。
欢迎测试给出反馈，预备下次优化可以解决。

**Comment by Samurais** [comment]
![image](https://user-images.githubusercontent.com/3538629/94803642-30d82880-041c-11eb-8998-bf57a8f0d32e.png)


![image](https://user-images.githubusercontent.com/3538629/94803668-39306380-041c-11eb-8958-7b1e34f1ccf4.png)
