### ISSUE TITLE
分词

### ISSUE THREAD

**Issue by codexuexi** [chatopera/Synonyms#114]
# 描述

## 功能

词向量的那个分词怎么整 [wordseg.py](https://github.com/Samurais/wikidata-corpus/blob/master/wordseg.py)
接口地址访问不了

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
使用其他分词完成，比如：
```
import synonyms
synonyms.seg(SENTENCE)
```
