### ISSUE TITLE
词向量文件一直下载不下来

### ISSUE THREAD

**Issue by iamxinxin** [chatopera/Synonyms#118]
词向量文件一直下载不下来，尝试了很多方法都没能下载下来。有没有好心人 扔给我个百度云或者Google drive的链接

**Comment by hailiang-wang** [comment]
查看首页 README.md 安装部分说明，设置
```
SYNONYMS_WORD2VEC_BIN_URL_ZH_CN
```

**Comment by Yin-1** [comment]
我想离线安装，初始化部分我该怎么操作呢

**Comment by hailiang-wang** [comment]
* 在一个有网络环境的机器 A，先下载完成词向量，注意打印日志包含了 Synonyms module 路径
* 复制机器 A 的 Synonyms module 路径到目标机器上

**Comment by hailiang-wang** [comment]
欢迎在此提供您的安装过程，以帮助将来有同样需求的使用者。 Thanks。

**Comment by fireice009** [comment]
库迁移了，请问下有没有新地址？
https://gitee.com/chatopera/cskefu/attach_files/610602/download/words.vector.gz
