### ISSUE TITLE
import errror,  load words.vector.gz failed, can't download completely

### ISSUE THREAD

**Issue by cindyhi** [chatopera/Synonyms#120]
Successfully installed synonyms-3.16.0
linux environment：
smart_open library not found; falling back to local-filesystem-only
[jieba] default dict file path ../data/vocab.txt
[jieba] default dict file path ../data/vocab.txt
[jieba] load default dict ../data/vocab.txt ...
[jieba] load default dict ../data/vocab.txt ...
>> Synonyms load wordseg dict [/home/jychen/anaconda3/envs/torch/lib/python3.7/site-packages/synonyms/data/vocab.txt] ... 
>> Synonyms on loading stopwords [/home/jychen/anaconda3/envs/torch/lib/python3.7/site-packages/synonyms/data/stopwords.txt] ...
[Synonyms] on loading vectors [/home/jychen/anaconda3/envs/torch/lib/python3.7/site-packages/synonyms/data/words.vector.gz] ...

[Synonyms] downloading data from https://gitee.com/chatopera/cskefu/attach_files/610602/download/words.vector.gz to /home/jychen/anaconda3/envs/torch/lib/python3.7/site-packages/synonyms/data/words.vector.gz ... 
 this only happens if SYNONYMS_WORD2VEC_BIN_URL_ZH_CN is not present and Synonyms initialization for the first time. 
 It would take minutes that depends on network.

OSError: [Errno socket error] [Errno socket error] [Errno -3] Temporary failure in name resolution

windows 10:
OSError: [Errno socket error] [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1076)

**Comment by cindyhi** [comment]
> Successfully installed synonyms-3.16.0
> linux environment：
> smart_open library not found; falling back to local-filesystem-only
> [jieba] default dict file path ../data/vocab.txt
> [jieba] default dict file path ../data/vocab.txt
> [jieba] load default dict ../data/vocab.txt ...
> [jieba] load default dict ../data/vocab.txt ...
> 
> > > Synonyms load wordseg dict [/home/jychen/anaconda3/envs/torch/lib/python3.7/site-packages/synonyms/data/vocab.txt] ...
> > > Synonyms on loading stopwords [/home/jychen/anaconda3/envs/torch/lib/python3.7/site-packages/synonyms/data/stopwords.txt] ...
> > > [Synonyms] on loading vectors [/home/jychen/anaconda3/envs/torch/lib/python3.7/site-packages/synonyms/data/words.vector.gz] ...
> 
> [Synonyms] downloading data from https://gitee.com/chatopera/cskefu/attach_files/610602/download/words.vector.gz to /home/jychen/anaconda3/envs/torch/lib/python3.7/site-packages/synonyms/data/words.vector.gz ...
> this only happens if SYNONYMS_WORD2VEC_BIN_URL_ZH_CN is not present and Synonyms initialization for the first time.
> It would take minutes that depends on network.
> 
> OSError: [Errno socket error] [Errno socket error] [Errno -3] Temporary failure in name resolution
> 
> windows 10:
> OSError: [Errno socket error] [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1076)

today it has changed to load words.vector.gz failed, can't  download completely:
 42% [.............................                                         ]  70934528 / 165919480Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jychen/anaconda3/envs/torch/lib/python3.7/site-packages/synonyms/__init__.py", line 14, in <module>
    from .synonyms import *
  File "/home/jychen/anaconda3/envs/torch/lib/python3.7/site-packages/synonyms/synonyms.py", line 149, in <module>
    _vectors = _load_w2v(model_file=_f_model)
  File "/home/jychen/anaconda3/envs/torch/lib/python3.7/site-packages/synonyms/synonyms.py", line 140, in _load_w2v
    wget.download(_f_url, out = model_file)
  File "/home/jychen/anaconda3/envs/torch/lib/python3.7/site-packages/synonyms/wget.py", line 313, in download
    (tmpfile, headers) = ThrowOnErrorOpener().retrieve(url, tmpfile, callback)
  File "/home/jychen/anaconda3/envs/torch/lib/python3.7/urllib/request.py", line 1867, in retrieve
    % (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 70930039 out of 165919480 bytes>

**Comment by hailiang-wang** [comment]
```
[Synonyms] downloading data from https://gitee.com/chatopera/cskefu/attach_files/610602/download/words.vector.gz to /home/jychen/anaconda3/envs/torch/lib/python3.7/site-packages/synonyms/data/words.vector.gz ...
```

Note, you can do this manually. Just download https://gitee.com/chatopera/cskefu/attach_files/610602/download/words.vector.gz with any tool, and put it with path /home/jychen/anaconda3/envs/torch/lib/python3.7/site-packages/synonyms/data/words.vector.gz

**Comment by cindyhi** [comment]
> ```
> [Synonyms] downloading data from https://gitee.com/chatopera/cskefu/attach_files/610602/download/words.vector.gz to /home/jychen/anaconda3/envs/torch/lib/python3.7/site-packages/synonyms/data/words.vector.gz ...
> ```
> 
> Note, you can do this manually. Just download https://gitee.com/chatopera/cskefu/attach_files/610602/download/words.vector.gz with any tool, and put it with path /home/jychen/anaconda3/envs/torch/lib/python3.7/site-packages/synonyms/data/words.vector.gz

Thank you for answering me.

**Comment by 666shencongli123** [comment]
离线下载words.vector.gz
百度网盘下载地址：链接: https://pan.baidu.com/s/1Ir6KIdjDGGl0QKR3Nk8yhA?pwd=fcak 提取码: fcak
然后复制到：/Users/dafengshen/opt/anaconda3/envs/torch_nightly_env/lib/python3.8/site-packages/synonyms/data/

**Comment by littleone01** [comment]
I have received your email, thanks a lot!
