### ISSUE TITLE
请问如何设置不输出：[Synonyms] not exist in w2v model

### ISSUE THREAD

**Issue by dannythebest** [chatopera/Synonyms#127]
## 描述

如图，使用synonyms.compare()计算相似度时，因为很多词不在语料库中，有 [Synonyms] not exist in w2v model 的提示，导致日志过大。请问能否设置该提示不输出？

<img width="398" alt="synonyms" src="https://user-images.githubusercontent.com/78265977/132148013-8e6128b5-5235-487b-845a-94d83c01c809.png">

**Comment by findoctor** [comment]
求问下这个问题解决了吗

**Comment by hailiang-wang** [comment]
没有解决，欢迎提交 PR ！
合并后会发布新版本，感谢！

**Comment by hailiang-wang** [comment]
Fix in release  3.17.0, install latest with
```
pip install -U synonyms
```
