### ISSUE TITLE
请问这个synonyms的计算相似度的公式是什么，采用什么思想计算相似度，看了很多文章都是应用，并没有介绍计算方式

### ISSUE THREAD

**Issue by young-yhx** [chatopera/Synonyms#138]
## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## Open Source for the World

[![banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/159913838-fbed2a14-a735-45b3-9e48-4727780a0d96.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
参考 https://github.com/chatopera/Synonyms/issues/64
