### ISSUE TITLE
如何使synonyms常驻进程？

### ISSUE THREAD

**Issue by ohblue** [chatopera/Synonyms#139]
每次调用synonyms进行相似度比较的时候，都要重新Building prefix和Loading model，耗时比较久
如何使synonyms常驻进程，这样其他脚本在调用compare()方法的时候不需要重复Building prefix和Loading model

**Comment by hailiang-wang** [comment]
可以构建一个 RestAPI 服务，启动后常驻。
Synonyms 项目关注相似度实现，如何常驻，其原理和普通 Python 程序一样。
欢迎 PR。
