### ISSUE TITLE
词向量文件下载链接已过期

### ISSUE THREAD

**Issue by Lawrence-Lu** [chatopera/Synonyms#140]
## 问题：
初次导入库过程中，词向量文件下载失败。
手动下载，链接已经403失效。
需要麻烦作者这边提供新的词向量文件下载链接。

<img width="810" alt="image" src="https://github.com/chatopera/Synonyms/assets/55588708/6a92595c-ab8f-431a-ae11-37ad176333f8">

<img width="596" alt="image" src="https://github.com/chatopera/Synonyms/assets/55588708/0a3cf1f1-3ec8-4b68-b185-ac8277a67919">

**Comment by patelrajnath** [comment]
Yes, same here..

**Comment by THustc2021** [comment]
UPDATE!!

**Comment by yuzhaopeng** [comment]
+1

**Comment by TheCutestCat** [comment]
@HebinHu 多谢分享，非常有用

**Comment by Niklauslxl** [comment]
@HebinHu 十分感谢

**Comment by littleone01** [comment]
I have received your email, thanks a lot!

**Comment by hailiang-wang** [comment]
update on latest version 
synonyms 3.20.0
https://pypi.org/project/synonyms/
