### ISSUE TITLE
word2vec-explorer 训练工具

### ISSUE THREAD

**Issue by Samurais** [chatopera/Synonyms#16]
# description

https://github.com/Samurais/word2vec-explorer

## expected

# solution

# environment

* version:
The commit hash (`git rev-parse HEAD`)

**Comment by upbit** [comment]
可以考虑用 https://github.com/harkous/embeddingsviz 可视化模型
通过Faiss搜寻近似向量，TensorBoard可视化

**Comment by Samurais** [comment]
👍 好的，看上去是在tensorflow里用，我还是倾向于用c版的word2vec。需要确认一下格式。距离计算方式也可以参考。谢谢。
