### ISSUE TITLE
ImportError when there's "utils" model

### ISSUE THREAD

**Issue by tcqiuyu** [chatopera/Synonyms#68]
# description
This has been resolved in pull#34 https://github.com/huyingxi/Synonyms/pull/34.

But in the most recent commits, this change is reverted and import will not work when there is utils package. 

## expected

# solution

# environment

* version:
The commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
已经使用 module 相对位置，请使用最新版本  3.15.0+
