### ISSUE TITLE
用nearby查处的是相关词，而不是同义词，有很多时候甚至是反义词

### ISSUE THREAD

**Issue by weihaixiaoseu** [chatopera/Synonyms#72]
# description
用nearby查处的是相关词，而不是同义词，有很多时候甚至是反义词，比如喜欢和讨厌
* version:
python 3.6.5

**Comment by samlet** [comment]
synonyms.display("购买")

'购买'近义词：
  1. 购买:1.0
  2. 出售:0.7971303
  3. 购置:0.72386324
  4. 卖给:0.70092577
  5. 购得:0.6998537
  6. 买到:0.6883096
  7. 购入:0.67976934
  8. 转售:0.67894334
  9. 购:0.6606151
  10. 借出:0.63738066

**Comment by huiguimoyu** [comment]
同意，我也正纳闷这个问题。。。怎么解决？

**Comment by kuangthree** [comment]
我也发现……
synonyms.display('富裕')
'富裕'近义词：
  1. 富裕:1.0
  2. 富足:0.734253
  3. 穷困:0.714261
  4. 中产阶级:0.712797
  5. 贫穷:0.711762
  6. 富有:0.681186
  7. 富人:0.656687
  8. 有钱:0.633914
  9. 贫苦:0.632235
  10. 殷实:0.604537

**Comment by jack1582** [comment]
用word2vec，挖出的是同类词。同义词，不太合适用word2vec。

**Comment by 9sunson** [comment]
的确是，只是相关词，而不是近义词。有没有输出近义词的方法呀。

**Comment by franplk** [comment]
> 用word2vec，挖出的是同类词。同义词，不太合适用word2vec。

那同义词查找一般使用什么技术呢？

**Comment by yan-rui** [comment]
> 用word2vec，挖出的是同类词。同义词，不太合适用word2vec。

准确地说说是 "同位词"
ABC, ADC--> A D 相似

**Comment by Samurais** [comment]
synonyms 趋向于使用非监督算法，所以，难以避免出现一些错误，尤其是近义词判断，暂时不作为优化方向。
欢迎贡献想法解决此问题！
