### ISSUE TITLE
3.8版本还出现 #46 bug

### ISSUE THREAD

**Issue by ConnieTong** [chatopera/Synonyms#76]
# description
synonyms version 3.8，但是还是出现#46 bug
## current
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\jieba-0.39-py3.5.egg\jieba\posseg\__init__.py", line 105, in load_word_tag
    word, _, tag = line.split(" ")
ValueError: too many values to unpack (expected 3)

## expected

# solution

# environment
windows
python 3.5.4
jieba 0.39
* version:
The commit hash (`git rev-parse HEAD`)

**Comment by DragonX081** [comment]
同样出现 感觉还是要把多词性的词改为单词性，不知会不会影响最后效果

**Comment by DragonX081** [comment]
我在import的时候用
` from synonyms.jieba import posseg `
就不报错了

**Comment by Samurais** [comment]
# related with #46

**Comment by Samurais** [comment]
帮忙测试一下 最新 v3.10.x

**Comment by Lanme** [comment]
很奇怪，我在3.6.2出现这个问题，然后虚拟环境是3.6.5，又没这样的问题，jieba和synonyms的版本都是一样的

**Comment by Lanme** [comment]
很奇怪，我在3.6.4出现这个问题，然后虚拟环境是3.6.5，又没这样的问题，jieba和synonyms的版本都是一样的，都是0.39和3.3.10

**Comment by Samurais** [comment]
Synonyms内部已经加入了jieba源码，不依赖于pip方式安装jieba。





——————
https://bot.chatopera.com
企业聊天机器人平台

------------------ 原始邮件 ------------------
发件人: Lanme <notifications@github.com>
发送时间: 2019年5月21日 10:30
收件人: huyingxi/Synonyms <Synonyms@noreply.github.com>
抄送: Samurais <hain@chatopera.com>, Comment <comment@noreply.github.com>
主题: 回复：[huyingxi/Synonyms] 3.8版本还出现 #46 bug (#76)




很奇怪，我在3.6.4出现这个问题，然后虚拟环境是3.6.5，又没这样的问题，jieba和synonyms的版本都是一样的，都是0.39和3.3.10

**Comment by Samurais** [comment]
3.15.0 版本中解决，感谢反馈！
