### ISSUE TITLE
How to add one couple of similar terms?

### ISSUE THREAD

**Issue by gaochao19860203** [chatopera/Synonyms#8]
如果 是想增加一对近义词，应该怎么操作？把这对近义词提交给你？或者 是否可以开放相关添加近义词的接口？

**Comment by Samurais** [comment]
现在近义词是有距离的，这也是计算句子间相似度的必要，而这个距离是word2vec计算出来的，我觉得增加api去添加近义词，不是很符合接口的一致性。实际中，是有这样的需求的，直接干扰近义词词表，但是这里要定义一个距离和词向量。
添加一对近义词 （A, B）,有下面的情况：
1）A,B 都不在当前词表中

2) A在词表中，B不在

3) A和B都在词表中

这几个情况，还需要认真思考一下怎么处理。目前我没有好的办法，所以还不能提供。

**Comment by gaochao19860203** [comment]
按照你说的思路，就是 先判断A，B两个词在不在词表中。如果A不在，将A与其他词的距离和词向量录入词表，B同理。是这样吗？
A与其他词的距离 可以用word2vec来计算，但是是不是需要包含A这个词的语料 才能计算？

**Comment by luoruisichuan** [comment]
软件功能很不错！
建议开放一个接口函数，自主添加词汇进去，比如，”病人“的向量是A，那么，自己可以添加”患者“，并将其向量设置为A，或者，在A的基础上，对向量中的元素人工做些修改，作为对应”患者“的向量。这样有利于软件的推广使用。
谢谢！
