### ISSUE TITLE
import jieba.analyse和import synonyms顺序

### ISSUE THREAD

**Issue by Lanme** [chatopera/Synonyms#84]
# description
首先我是想调用jieba的词典而不是synonyms的词典，所以就需要两个模块都存在。在导入模块的时候，顺序一：import jieba.analyse import synonyms 没错；顺序二：import synonyms import jieba.analyse 报错，报错理由是：

>>>import synonyms
Synonyms load wordseg dict [/user/installs/anaconda3/lib/python3.6/site-packages/synonyms/data/vocab.txt] ...
Building prefix dict from /user/installs/anaconda3/lib/python3.6/site-packages/synonyms/data/vocab.txt ...
WARNING: Logging before flag parsing goes to stderr.
I0521 15:29:06.467896 140490022262592 __init__.py:111] Building prefix dict from /user/installs/anaconda3/lib/python3.6/site-packages/synonyms/data/vocab.txt ...
Dumping model to file cache /tmp/jieba.u31c778e171f7cab1ab7a5690e21d6d50.cache
I0521 15:29:07.947464 140490022262592 __init__.py:145] Dumping model to file cache /tmp/jieba.u31c778e171f7cab1ab7a5690e21d6d50.cache
Loading model cost 1.586 seconds.
I0521 15:29:08.054000 140490022262592 __init__.py:163] Loading model cost 1.586 seconds.
Prefix dict has been built succesfully.
I0521 15:29:08.054174 140490022262592 __init__.py:164] Prefix dict has been built succesfully.
>> Synonyms on loading stopwords [/user/installs/anaconda3/lib/python3.6/site-packages/synonyms/data/stopwords.txt] ...
>> Synonyms on loading vectors [/user/installs/anaconda3/lib/python3.6/site-packages/synonyms/data/words.vector] ...

>>>import jieba
>>>import jieba.analyse
Traceback (most recent call last):
  File "/user/installs/anaconda3/lib/python3.6/site-packages/jieba/posseg/__init__.py", line 105, in load_word_tag
    word, _, tag = line.split(" ")
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/user/installs/anaconda3/lib/python3.6/site-packages/jieba/analyse/__init__.py", line 2, in <module>
    from .tfidf import TFIDF
  File "/user/installs/anaconda3/lib/python3.6/site-packages/jieba/analyse/tfidf.py", line 5, in <module>
    import jieba.posseg
  File "/user/installs/anaconda3/lib/python3.6/site-packages/jieba/posseg/__init__.py", line 257, in <module>
    dt = POSTokenizer(jieba.dt)
  File "/user/installs/anaconda3/lib/python3.6/site-packages/jieba/posseg/__init__.py", line 82, in __init__
    self.load_word_tag(self.tokenizer.get_dict_file())
  File "/user/installs/anaconda3/lib/python3.6/site-packages/jieba/posseg/__init__.py", line 109, in load_word_tag
    'invalid POS dictionary entry in %s at Line %s: %s' % (f_name, lineno, line))
ValueError: invalid POS dictionary entry in /user/installs/anaconda3/lib/python3.6/site-packages/synonyms/data/vocab.txt at Line 5008: 『 1 v 2 w

>>> jieba
<module 'jieba' from '/user/installs/anaconda3/lib/python3.6/site-packages/jieba/__init__.py'>

# environment
python 3.6.4
jieba 0.39
synonyms 3.10.2

**Comment by macleo** [comment]
good job [https://www.lunwen66.com](url)

**Comment by AlucardNosferatu** [comment]
same problem
