### ISSUE TITLE
AttributeError: module 'synonyms' has no attribute 'seg'

### ISSUE THREAD

**Issue by KevinChen1994** [chatopera/Synonyms#85]
# description
Python 3.6 。通过pip install 安装，安装成功，但是调用分词和同义词等都不能使用，报错AttributeError: module 'synonyms' has no attribute 'seg'
## expected

# solution

# environment
python 3.6
* version:
3.10.2
The commit hash (`git rev-parse HEAD`)

**Comment by Dorado607** [comment]
我也遇到了同样的问题，python3.6，3.10.X都试过了

**Comment by Dorado607** [comment]
作者大大能回答下吗？用不了呀？

**Comment by liuguoxionglang** [comment]
python3.7.4 
synonyms 3.10.2
也是报错 
module 'synonyms' has no attribute 'compare'
