### ISSUE TITLE
目前安装失败

### ISSUE THREAD

**Issue by sxgkwei** [chatopera/Synonyms#98]
python版本：3.8.0
操作系统: win 7 64位
安装命令：pip install -U synonyms
错误提示：
`Collecting synonyms
  Using cached https://files.pythonhosted.org/packages/3e/47/065b8f34aad7bbf34447df72e4188a5ac6ae7106af5e2f91f5a0ed33f4e0/synonyms-3.10.2.tar.gz
Requirement already satisfied, skipping upgrade: six>=1.11.0 in e:\python\python38-32\lib\site-packages (from synonyms) (1.13.0)
Requirement already satisfied, skipping upgrade: numpy>=1.13.1 in e:\python\python38-32\lib\site-packages (from synonyms) (1.17.4)
Requirement already satisfied, skipping upgrade: scipy>=1.0.0 in e:\python\python38-32\lib\site-packages (from synonyms) (1.3.3)
Collecting scikit-learn>=0.19.1
  Using cached https://files.pythonhosted.org/packages/1e/ce/9d8c88e68af0a5b5c5d78d8d2b7bcadfd45e1d6afc863ccb9aee30765b06/scikit-learn-0.21.3.tar.gz
Collecting absl-py>=0.4
  Using cached https://files.pythonhosted.org/packages/3b/72/e6e483e2db953c11efa44ee21c5fdb6505c4dffa447b4263ca8af6676b62/absl-py-0.8.1.tar.gz
Requirement already satisfied, skipping upgrade: joblib>=0.11 in e:\python\python38-32\lib\site-packages (from scikit-learn>=0.19.1->synonyms) (0.14.0)
Installing collected packages: scikit-learn, absl-py, synonyms
    Running setup.py install for scikit-learn ... error
    ERROR: Command errored out with exit status 1:
     command: 'e:\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-i_vp24_d\\scikit-learn\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-i_vp24_d\\scikit-learn\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C
:\Users\Administrator\AppData\Local\Temp\pip-record-o8dfx0rq\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Administrator\AppData\Local\Temp\pip-install-i_vp24_d\scikit-learn\
    Complete output (28 lines):
    Partial import of sklearn during the build process.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Administrator\AppData\Local\Temp\pip-install-i_vp24_d\scikit-learn\setup.py", line 290, in <module>
        setup_package()
      File "C:\Users\Administrator\AppData\Local\Temp\pip-install-i_vp24_d\scikit-learn\setup.py", line 286, in setup_package
        setup(**metadata)
      File "e:\python\python38-32\lib\site-packages\numpy\distutils\core.py", line 137, in setup
        config = configuration()
      File "C:\Users\Administrator\AppData\Local\Temp\pip-install-i_vp24_d\scikit-learn\setup.py", line 174, in configuration
        config.add_subpackage('sklearn')
      File "e:\python\python38-32\lib\site-packages\numpy\distutils\misc_util.py", line 1033, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "e:\python\python38-32\lib\site-packages\numpy\distutils\misc_util.py", line 999, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "e:\python\python38-32\lib\site-packages\numpy\distutils\misc_util.py", line 941, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "sklearn\setup.py", line 62, in configuration
        config.add_subpackage('utils')
      File "e:\python\python38-32\lib\site-packages\numpy\distutils\misc_util.py", line 1033, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "e:\python\python38-32\lib\site-packages\numpy\distutils\misc_util.py", line 999, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "e:\python\python38-32\lib\site-packages\numpy\distutils\misc_util.py", line 941, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "sklearn\utils\setup.py", line 8, in configuration
        from Cython import Tempita
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'e:\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-i_vp24_d\\scikit-learn\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-i_vp24_d\\scikit-learn\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"
'exec'"'"'))' install --record 'C:\Users\Administrator\AppData\Local\Temp\pip-record-o8dfx0rq\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.`

**Comment by Samurais** [comment]
```
ModuleNotFoundError: No module named 'Cython' ---------------------------------------- ERROR: Command errored out with exit status 1: 'e:\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-i_vp24_d\\scikit-learn\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-

```


并不是本包导致，请确认该环境 scikit-learn 可以安装。我用的 python 是 3.6, 3.7, 3.5, 2.7, Mac OSX, Linux.
