### ISSUE TITLE
载入vocab.txt时报错（2019.12.11）

### ISSUE THREAD

**Issue by Sewens** [chatopera/Synonyms#99]
# description
在flask中使用synonyms时发生错误，vocab.txt问题，和之前的类似。

ValueError: invalid POS dictionary entry in /home/lawbda/env/anaconda3/lib/python3.6/site-packages/synonyms/data/vocab.txt at Line 5008: 『 1 v 2 w

# error message

>> Synonyms on loading stopwords [/home/lawbda/env/anaconda3/lib/python3.6/site-packages/synonyms/data/stopwords.txt] ...
>> Synonyms on loading vectors [/home/lawbda/env/anaconda3/lib/python3.6/site-packages/synonyms/data/words.vector] ...
ERROR:connexion.apis.abstract:Failed to add operation for GET /Lawbda/dataWare/1.0.0/weibo/searchComment
Traceback (most recent call last):
  File "/home/lawbda/env/anaconda3/lib/python3.6/site-packages/connexion/apis/abstract.py", line 207, in add_paths
    self.add_operation(path, method)
  File "/home/lawbda/env/anaconda3/lib/python3.6/site-packages/connexion/apis/abstract.py", line 171, in add_operation
    pass_context_arg_name=self.pass_context_arg_name
  File "/home/lawbda/env/anaconda3/lib/python3.6/site-packages/connexion/operations/__init__.py", line 8, in make_operation
    return spec.operation_cls.from_spec(spec, *args, **kwargs)
  File "/home/lawbda/env/anaconda3/lib/python3.6/site-packages/connexion/operations/swagger2.py", line 137, in from_spec
    **kwargs
  File "/home/lawbda/env/anaconda3/lib/python3.6/site-packages/connexion/operations/swagger2.py", line 96, in __init__
    pass_context_arg_name=pass_context_arg_name
  File "/home/lawbda/env/anaconda3/lib/python3.6/site-packages/connexion/operations/abstract.py", line 98, in __init__
    self._resolution = resolver.resolve(self)
  File "/home/lawbda/env/anaconda3/lib/python3.6/site-packages/connexion/resolver.py", line 40, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/home/lawbda/env/anaconda3/lib/python3.6/site-packages/connexion/resolver.py", line 66, in resolve_function_from_operation_id
    raise ResolverError(str(e), sys.exc_info())
connexion.exceptions.ResolverError: <ResolverError: invalid POS dictionary entry in /home/lawbda/env/anaconda3/lib/python3.6/site-packages/synonyms/data/vocab.txt at Line 5008: 『 1 v 2 w>

# environment
* version:
The commit hash (`git rev-parse HEAD`)
python 3.6.8
synonyms 3.3.10

**Comment by Refrainlhy** [comment]
解决了吗

**Comment by Sewens** [comment]
没解决啊。。没法定位到底是哪里错了。

**Comment by Skyline5723** [comment]
@Sewens @Refrainlhy  我把jieba的源码改了，好像能用了，可以试一试
    首先找到"...\venvs\xxx\Lib\site-packages\jieba\posseg\__init__.py"文件，可以根据报错信息“invalid POS dictionary entry in %s at Line %s: %s”定位到该文件，再找到其中的load_word_tag函数，把 word, _, tag = line.split(" ") 这一行改成 word, _, tag = line.split(" ")[:3]。

**Comment by Sewens** [comment]
> @Sewens @Refrainlhy 我把jieba的源码改了，好像能用了，可以试一试
> 首先找到"...\venvs\xxx\Lib\site-packages\jieba\posseg__init__.py"文件，可以根据报错信息“invalid POS dictionary entry in %s at Line %s: %s”定位到该文件，再找到其中的load_word_tag函数，把 word, _, tag = line.split(" ") 这一行改成 word, _, tag = line.split(" ")[:3]。

感谢感谢！我去试试看。

**Comment by sralvins** [comment]
作者把jieba0.39版本直接放进了自己的代码里，并可能修改了一些代码。

导入vocab、分词时，用的是synonyms包里的jieba，synonyms包里jieba导入词典的代码是这样：
![s1](https://user-images.githubusercontent.com/24619551/93308945-81089580-f835-11ea-9222-cf2951bb2b2d.png)

而jieba(0.42.1)里这部分是这样
![s2](https://user-images.githubusercontent.com/24619551/93309054-a4334500-f835-11ea-9384-b8152b189e54.png)

作者可能为了load vocab不报错（还是说0.39版本的jieba就那样）就直接wrap了0.39版本的jieba到自己代码里，但代码里同样还用到了原本jieba库。由于jieba的缓存机制导致了一些异常行为。感觉这样不太妥。

总之，synonyms包里的vocab.txt文本5008行文本不规范。每行应该是“word freq tag”。

**Comment by ficknico** [comment]
> 作者把jieba0.39版本直接放进了自己的代码里，并可能修改了一些代码。
> 
> 导入vocab、分词时，用的是synonyms包里的jieba，synonyms包里jieba导入词典的代码是这样：
> ![s1](https://user-images.githubusercontent.com/24619551/93308945-81089580-f835-11ea-9222-cf2951bb2b2d.png)
> 
> 而jieba(0.42.1)里这部分是这样
> ![s2](https://user-images.githubusercontent.com/24619551/93309054-a4334500-f835-11ea-9384-b8152b189e54.png)
> 
> 作者可能为了load vocab不报错（还是说0.39版本的jieba就那样）就直接复制了0.39版本的jieba到自己代码里并做了一些修改，但代码里还用到了原本jieba库。由于jieba的缓存机制导致了一些异常行为。感觉这样不太妥。
> 
> 总之，synonyms包里的vocab.txt文本不符合jieba.posseg导入词典的规范。jieba要求每行应该是“word freq tag”，而synonyms包里的vocab.txt，同一个词有多个pos_tag的话都放在了一行，所以load时会出错。

我也遇到了同样问题加载报错。但我发发现他用的jieba是我本地的jieba，没有用他包里自带的。也对比了一下我本地的jieba和他包里的jieba确实[:3]，我本地没有这项。那是不是不用local 的jieba就没这问题了？直接改local 的jieba感觉不好。但如何让他用包里的jieba楼主知道怎么操作不？谢谢

**Comment by sralvins** [comment]
> > 作者把jieba0.39版本直接放进了自己的代码里，并可能修改了一些代码。
> > 导入vocab、分词时，用的是synonyms包里的jieba，synonyms包里jieba导入词典的代码是这样：
> > ![s1](https://user-images.githubusercontent.com/24619551/93308945-81089580-f835-11ea-9222-cf2951bb2b2d.png)
> > 而jieba(0.42.1)里这部分是这样
> > ![s2](https://user-images.githubusercontent.com/24619551/93309054-a4334500-f835-11ea-9384-b8152b189e54.png)
> > 作者可能为了load vocab不报错（还是说0.39版本的jieba就那样）就直接复制了0.39版本的jieba到自己代码里并做了一些修改，但代码里还用到了原本jieba库。由于jieba的缓存机制导致了一些异常行为。感觉这样不太妥。
> > 总之，synonyms包里的vocab.txt文本不符合jieba.posseg导入词典的规范。jieba要求每行应该是“word freq tag”，而synonyms包里的vocab.txt，同一个词有多个pos_tag的话都放在了一行，所以load时会出错。
> 
> 我也遇到了同样问题加载报错。但我发发现他用的jieba是我本地的jieba，没有用他包里自带的。也对比了一下我本地的jieba和他包里的jieba确实[:3]，我本地没有这项。那是不是不用local 的jieba就没这问题了？直接改local 的jieba感觉不好。但如何让他用包里的jieba楼主知道怎么操作不？谢谢

用的话可以把`vocab.txt`改了。改成每行都是`word freq pos_tag`的形式。import synonyms时，这个包会把自己安装目录放在sys.path第一个，后面再import jieba用的是包里的jieba。先import jieba，再import synonyms，这个包的代码里也会用你自己装的jieba，就会报错，因为系统jieba没法load`vocab.txt`。我的建议是不要用这个包。。。里面直接copy了jieba和gensim的代码，你看下代码就知道怎么回事，然后自己实现呗。我也不知道为什么不把这两个包做依赖包，而是直接把别人代码放到自己代码里是什么逻辑。。。

**Comment by ficknico** [comment]
> > > 作者把jieba0.39版本直接放进了自己的代码里，并可能修改了一些代码。
> > > 导入vocab、分词时，用的是synonyms包里的jieba，synonyms包里jieba导入词典的代码是这样：
> > > ![s1](https://user-images.githubusercontent.com/24619551/93308945-81089580-f835-11ea-9222-cf2951bb2b2d.png)
> > > 而jieba(0.42.1)里这部分是这样
> > > ![s2](https://user-images.githubusercontent.com/24619551/93309054-a4334500-f835-11ea-9384-b8152b189e54.png)
> > > 作者可能为了load vocab不报错（还是说0.39版本的jieba就那样）就直接复制了0.39版本的jieba到自己代码里并做了一些修改，但代码里还用到了原本jieba库。由于jieba的缓存机制导致了一些异常行为。感觉这样不太妥。
> > > 总之，synonyms包里的vocab.txt文本不符合jieba.posseg导入词典的规范。jieba要求每行应该是“word freq tag”，而synonyms包里的vocab.txt，同一个词有多个pos_tag的话都放在了一行，所以load时会出错。
> > 
> > 
> > 我也遇到了同样问题加载报错。但我发发现他用的jieba是我本地的jieba，没有用他包里自带的。也对比了一下我本地的jieba和他包里的jieba确实[:3]，我本地没有这项。那是不是不用local 的jieba就没这问题了？直接改local 的jieba感觉不好。但如何让他用包里的jieba楼主知道怎么操作不？谢谢
> 
> 用的话可以把`vocab.txt`改了。改成每行都是`word freq pos_tag`的形式。import synonyms时，这个包会把自己安装目录放在sys.path第一个，后面再import jieba用的是包里的jieba。先import jieba，再import synonyms，这个包的代码里也会用你自己装的jieba，就会报错，因为系统jieba没法load`vocab.txt`。我的建议是不要用这个包。。。里面直接copy了jieba和gensim的代码，你看下代码就知道怎么回事，然后自己实现呗。我也不知道为什么不把这两个包做依赖包，而是直接把别人代码放到自己代码里是什么逻辑。。。

多谢多谢，之前只定点关注这个问题，没有细看其他部分。好的，我细细看看源码去。是啊，有依赖挂上多好，方便你我他。哈哈，至于作者怎么想的，我们等他出来座谈一下 @.@

**Comment by Samurais** [comment]
已经解决。使用最新版  3.15.0+
